/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SensorType {
    SensorType_NONE = 0,
    /* * Onboard power measurements */
    SensorType_POWER_VOLTAGE = 1,
    SensorType_POWER_CURRENT = 2,
    /* * Teros12 measurements */
    SensorType_TEROS12_VWC = 3,
    SensorType_TEROS12_VWC_ADJ = 4,
    SensorType_TEROS12_TEMP = 5,
    SensorType_TEROS12_EC = 6,
    /* * Phytos31 measurements */
    SensorType_PHYTOS31_VOLTAGE = 7,
    SensorType_PHYTOS31_LEAF_WETNESS = 8,
    /* * Bme280 measurements */
    SensorType_BME280_PRESSURE = 9,
    SensorType_BME280_TEMP = 10,
    SensorType_BME280_HUMIDITY = 11,
    /* * Teros21 measurements */
    SensorType_TEROS21_MATRIC_POT = 12,
    SensorType_TEROS21_TEMP = 13,
    /* * Sen0308 measurements */
    SensorType_SEN0308_VOLTAGE = 14,
    SensorType_SEN0308_HUMIDITY = 15,
    /* * Sen0257 measurements */
    SensorType_SEN0257_VOLTAGE = 16,
    SensorType_SEN0257_PRESSURE = 17,
    /* * YFS210C measurements */
    SensorType_YFS210C_FLOW = 18,
    /* * PCAP02 measurements */
    SensorType_PCAP02_CAPACITANCE = 19
} SensorType;

typedef enum _SensorError {
    /* No error */
    SensorError_OK = 0,
    /* General error for all other errors */
    SensorError_GENERAL = 1,
    /* Logger id not found */
    SensorError_LOGGER = 2,
    /* Cell id not found */
    SensorError_CELL = 3,
    /* Sensor type not recognized */
    SensorError_UNSUPPORTED = 4,
    /* Invalid format of message */
    SensorError_INVALID = 5,
    /* Decode error */
    SensorError_DECODE = 6
} SensorError;

/* Struct definitions */
typedef struct _Metadata {
    /* id of the cell measured */
    uint32_t cell_id;
    /* id of the logging device */
    uint32_t logger_id;
    /* timestamp of the measurement */
    uint32_t ts;
} Metadata;

typedef struct _SensorResponse {
    /* Index of measurements */
    uint32_t idx;
    /* Error code */
    SensorError error;
} SensorResponse;

typedef struct _RepeatedSensorResponses {
    pb_size_t responses_count;
    SensorResponse responses[16];
} RepeatedSensorResponses;

typedef struct _SensorMeasurement {
    /* * Metadata for the measurement */
    bool has_meta;
    Metadata meta;
    /* * Type of sensor measurement */
    SensorType type;
    pb_size_t which_value;
    union {
        uint32_t unsigned_int;
        int32_t signed_int;
        double decimal;
    } value;
    /* * Index of the measurement */
    uint32_t idx;
} SensorMeasurement;

typedef struct _RepeatedSensorMeasurements {
    /* * Metadata for all measurements */
    bool has_meta;
    Metadata meta;
    /* * Type of sensor measurements */
    SensorType type;
    /* * List of sensor measurements */
    pb_size_t measurements_count;
    SensorMeasurement measurements[16];
} RepeatedSensorMeasurements;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SensorType_MIN SensorType_NONE
#define _SensorType_MAX SensorType_PCAP02_CAPACITANCE
#define _SensorType_ARRAYSIZE ((SensorType)(SensorType_PCAP02_CAPACITANCE+1))

#define _SensorError_MIN SensorError_OK
#define _SensorError_MAX SensorError_DECODE
#define _SensorError_ARRAYSIZE ((SensorError)(SensorError_DECODE+1))


#define SensorResponse_error_ENUMTYPE SensorError


#define SensorMeasurement_type_ENUMTYPE SensorType

#define RepeatedSensorMeasurements_type_ENUMTYPE SensorType


/* Initializer values for message structs */
#define Metadata_init_default                    {0, 0, 0}
#define SensorResponse_init_default              {0, _SensorError_MIN}
#define RepeatedSensorResponses_init_default     {0, {SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default, SensorResponse_init_default}}
#define SensorMeasurement_init_default           {false, Metadata_init_default, _SensorType_MIN, 0, {0}, 0}
#define RepeatedSensorMeasurements_init_default  {false, Metadata_init_default, _SensorType_MIN, 0, {SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default, SensorMeasurement_init_default}}
#define Metadata_init_zero                       {0, 0, 0}
#define SensorResponse_init_zero                 {0, _SensorError_MIN}
#define RepeatedSensorResponses_init_zero        {0, {SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero, SensorResponse_init_zero}}
#define SensorMeasurement_init_zero              {false, Metadata_init_zero, _SensorType_MIN, 0, {0}, 0}
#define RepeatedSensorMeasurements_init_zero     {false, Metadata_init_zero, _SensorType_MIN, 0, {SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero, SensorMeasurement_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Metadata_cell_id_tag                     1
#define Metadata_logger_id_tag                   2
#define Metadata_ts_tag                          3
#define SensorResponse_idx_tag                   1
#define SensorResponse_error_tag                 2
#define RepeatedSensorResponses_responses_tag    1
#define SensorMeasurement_meta_tag               1
#define SensorMeasurement_type_tag               2
#define SensorMeasurement_unsigned_int_tag       3
#define SensorMeasurement_signed_int_tag         4
#define SensorMeasurement_decimal_tag            5
#define SensorMeasurement_idx_tag                6
#define RepeatedSensorMeasurements_meta_tag      1
#define RepeatedSensorMeasurements_type_tag      2
#define RepeatedSensorMeasurements_measurements_tag 3

/* Struct field encoding specification for nanopb */
#define Metadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cell_id,           1) \
X(a, STATIC,   SINGULAR, UINT32,   logger_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   ts,                3)
#define Metadata_CALLBACK NULL
#define Metadata_DEFAULT NULL

#define SensorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   idx,               1) \
X(a, STATIC,   SINGULAR, UENUM,    error,             2)
#define SensorResponse_CALLBACK NULL
#define SensorResponse_DEFAULT NULL

#define RepeatedSensorResponses_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  responses,         1)
#define RepeatedSensorResponses_CALLBACK NULL
#define RepeatedSensorResponses_DEFAULT NULL
#define RepeatedSensorResponses_responses_MSGTYPE SensorResponse

#define SensorMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   ONEOF,    UINT32,   (value,unsigned_int,value.unsigned_int),   3) \
X(a, STATIC,   ONEOF,    INT32,    (value,signed_int,value.signed_int),   4) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,decimal,value.decimal),   5) \
X(a, STATIC,   SINGULAR, UINT32,   idx,               6)
#define SensorMeasurement_CALLBACK NULL
#define SensorMeasurement_DEFAULT NULL
#define SensorMeasurement_meta_MSGTYPE Metadata

#define RepeatedSensorMeasurements_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  measurements,      3)
#define RepeatedSensorMeasurements_CALLBACK NULL
#define RepeatedSensorMeasurements_DEFAULT NULL
#define RepeatedSensorMeasurements_meta_MSGTYPE Metadata
#define RepeatedSensorMeasurements_measurements_MSGTYPE SensorMeasurement

extern const pb_msgdesc_t Metadata_msg;
extern const pb_msgdesc_t SensorResponse_msg;
extern const pb_msgdesc_t RepeatedSensorResponses_msg;
extern const pb_msgdesc_t SensorMeasurement_msg;
extern const pb_msgdesc_t RepeatedSensorMeasurements_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Metadata_fields &Metadata_msg
#define SensorResponse_fields &SensorResponse_msg
#define RepeatedSensorResponses_fields &RepeatedSensorResponses_msg
#define SensorMeasurement_fields &SensorMeasurement_msg
#define RepeatedSensorMeasurements_fields &RepeatedSensorMeasurements_msg

/* Maximum encoded size of messages (where known) */
#define Metadata_size                            18
#define RepeatedSensorMeasurements_size          678
#define RepeatedSensorResponses_size             160
#define SENSOR_PB_H_MAX_SIZE                     RepeatedSensorMeasurements_size
#define SensorMeasurement_size                   39
#define SensorResponse_size                      8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
