/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "soil_power_sensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MeasurementMetadata, MeasurementMetadata, AUTO)


PB_BIND(PowerMeasurement, PowerMeasurement, AUTO)


PB_BIND(VoltageDeltaMeasurement, VoltageDeltaMeasurement, AUTO)


PB_BIND(CurrentDeltaMeasurement, CurrentDeltaMeasurement, AUTO)


PB_BIND(VoltageMeasurement, VoltageMeasurement, AUTO)


PB_BIND(CurrentMeasurement, CurrentMeasurement, AUTO)


PB_BIND(PowerDeltaEntry, PowerDeltaEntry, AUTO)


PB_BIND(PowerMeasurementDelta, PowerMeasurementDelta, AUTO)


PB_BIND(RepeatedPowerDeltas, RepeatedPowerDeltas, AUTO)


PB_BIND(Teros12Measurement, Teros12Measurement, AUTO)


PB_BIND(Teros21Measurement, Teros21Measurement, AUTO)


PB_BIND(Phytos31Measurement, Phytos31Measurement, AUTO)


PB_BIND(BME280Measurement, BME280Measurement, AUTO)


PB_BIND(SEN0308Measurement, SEN0308Measurement, AUTO)


PB_BIND(SEN0257Measurement, SEN0257Measurement, AUTO)


PB_BIND(YFS210CMeasurement, YFS210CMeasurement, AUTO)


PB_BIND(PCAP02Measurement, PCAP02Measurement, AUTO)


PB_BIND(Measurement, Measurement, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(Esp32Command, Esp32Command, 2)


PB_BIND(PageCommand, PageCommand, AUTO)


PB_BIND(TestCommand, TestCommand, AUTO)


PB_BIND(WiFiCommand, WiFiCommand, 2)


PB_BIND(UserConfigCommand, UserConfigCommand, 2)


PB_BIND(MicroSDCommand, MicroSDCommand, 2)


PB_BIND(IrrigationCommand, IrrigationCommand, AUTO)


PB_BIND(PowerCommand, PowerCommand, AUTO)


PB_BIND(UserConfiguration, UserConfiguration, AUTO)


PB_BIND(adcValue, adcValue, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
